In [1]:
with open('dataset.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("leght of dataset in characters: ", len(text))

leght of dataset in characters:  172468245


In [3]:
# Let's see the first 1000 characters
print(text[:1000])

Title: प्रार्थना

मेरे पाँव के पास चाँदनी बिछाओ भगवान !
दूज के चाँद पर मुझे खड़ा करो
किसी महाराजा के समान ।
टखने डूबे हों चाँदनी में,

मेरे मोजे मुलायम,चमकदार हों ;
और मेरे मस्तक पर
चाँदनी की झरती फुहार हो ।
शीतलता पर इतराऊँ, चमक पर मचलूँ

चाँदनी में तैरता हुआ मंजिल की ओर चलूँ ।
क्योंकि सूरज काल हो गया है ।
उसका चेहर शेर के समान लाल हो गया है ।
2.  एकान्त

लोग अकेलेपन की शिकायत करते हैं ।
मैं समझ नहीं पाता ,
वे किस बात से डरते हैं ।
अकेलापन तो जीवन का चरम आनन्द है ।

जो हैं निःसंग,
सोचो तो, वही स्वच्छंद है ।
अकेला होने पर जगते हैं विचार;
ऊपर आती है उठकर

अंधकार से नीली झंकार ।
जो है अकेला,
करता है अपना छोटा-मोटा काम,
या लेता हुआ आराम,

झाँक कर देखता है आगे की राह को,
पहुँच से बाहर की दुनिया अथाह को;
तत्वों के केन्द्र-बिन्दु से होकर एकतान
बिना किसी बाधा के करता है ध्यान

विषम के बीच छिपे सम का,
अपने उदगम का ।
3.  अकेलेपन का आनन्द
अकेलेपन से बढ़कर

आनन्द नहीं , आराम नहीं ।
स्वर्ग है वह एकान्त,
जहाँ शोर नहीं, धूमधाम नहीं ।
देश और काल के प्रसार में,

शून्यता, अशब्दता अपार में
चाँद जब घूमता

In [4]:
# All the unique characters in the file
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print('Number of unique characters: ', vocab_size)



 !"'()+,-.0123456789:;=?CTU[]aceilnost|¸ँंःअआइईउऊऋऎएऐओऔकखगघङचछजझञटठडढणतथदधनपफबभमयरलवशषसह़ऽािीुूृॄॅेैॉॊोौ्क़ग़ज़ड़ढ़फ़ॠ।॥०१२३४५६७८९॰‌‍–‘’“”…
Number of unique characters:  134


In [5]:
# create a mapping of unique characters to integers
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for i, ch in enumerate(chars)}
encode = lambda s: [stoi[c] for c in s]          # encoder: string -> list of integers
decode = lambda x: ''.join([itos[i] for i in x]) # decoder: list of integers -> string

print(encode('शून्यता'))
print(decode(encode('शून्यता')))

[85, 95, 75, 105, 81, 71, 91]
शून्यता


In [6]:
# Let's encode the whole text
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.size())
print(data[:1000])        # the 1000 first characters, encoded as integers

torch.Size([172468245])
tensor([ 26,  33,  38,  34,  32,  21,   1,  76, 105,  82,  91,  82, 105,  72,
         75,  91,   0,   0,  80,  99,  82,  99,   1,  76,  91,  41,  84,   1,
         56,  99,   1,  76,  91,  87,   1,  61,  91,  41,  73,  75,  93,   1,
         78,  92,  62,  91,  54,   1,  79,  58,  84,  91,  75,   1,   2,   0,
         73,  95,  63,   1,  56,  99,   1,  61,  91,  41,  73,   1,  76,  82,
          1,  80,  94,  64,  99,   1,  57,  68,  89,  91,   1,  56,  82, 103,
          0,  56,  92,  87,  93,   1,  80,  88,  91,  82,  91,  63,  91,   1,
         56,  99,   1,  87,  80,  91,  75,   1, 113,   0,  66,  57,  75,  99,
          1,  68,  95,  78,  99,   1,  88, 103,  42,   1,  61,  91,  41,  73,
         75,  93,   1,  80,  99,  42,   8,   0,   0,  80,  99,  82,  99,   1,
         80, 103,  63,  99,   1,  80,  94,  83,  91,  81,  80,   8,  61,  80,
         56,  73,  91,  82,   1,  88, 103,  42,   1,  22,   0,  55,  82,   1,
         80,  99,  82,  99,   1,  80,  8

In [7]:
# Let's now split the data into training and validation sets
n = int(0.9 * len(data))                        # 90% of the data for training and 10% for validation
train_data, val_data = data[:n], data[n:]

In [8]:
block_size = 8                      # context length
train_data[:block_size+1]
decode(train_data[:block_size+1].tolist())

'Title: प्'

In [9]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context, target = x[:t+1], y[:t]
    # print(f"When input is {decode(context.tolist())}, target is {decode(target.tolist())}")         # uncomment to see the data
    print(f"When input is {context}, target is {target}")
    

When input is tensor([26]), target is tensor([], dtype=torch.int64)
When input is tensor([26, 33]), target is tensor([33])
When input is tensor([26, 33, 38]), target is tensor([33, 38])
When input is tensor([26, 33, 38, 34]), target is tensor([33, 38, 34])
When input is tensor([26, 33, 38, 34, 32]), target is tensor([33, 38, 34, 32])
When input is tensor([26, 33, 38, 34, 32, 21]), target is tensor([33, 38, 34, 32, 21])
When input is tensor([26, 33, 38, 34, 32, 21,  1]), target is tensor([33, 38, 34, 32, 21,  1])
When input is tensor([26, 33, 38, 34, 32, 21,  1, 76]), target is tensor([33, 38, 34, 32, 21,  1, 76])


In [10]:
torch.manual_seed(1337)
batch_size = 4               # how many independent sequences to train on in parallel                 
block_size = 8               # what is the context length for prediction

def get_batch(split):
    # generate a small batch of data of input x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,)) # starting index of each sequence
    x = torch.stack([data[i:i+block_size] for i in ix])       # input sequences
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])   # target sequences, i.e. shifted by 1
    return x, y
    
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)                                                     
# print(decode(xb[0].tolist()))
print('targets:')
print(yb.shape)
print(yb)
# print(decode(yb[0].tolist()))

print('-----------------')

for b in range(batch_size):                                     # iterate over batch dimension
    for t in range(block_size):                                 # iterate over time dimension
        context, target = xb[b, :t+1], yb[b, t]
        print(f"When input is {context.tolist()}, target is {target}")
        # print(f"When input is {decode(context.tolist())}, target is {decode([target.tolist()])}")

inputs:
torch.Size([4, 8])
tensor([[ 91,  82,  91,   1,  85, 103,  70,  92],
        [ 71,  94,  80, 105,  88,  91,  82,  91],
        [ 91,  87,   8,   0,  75,   1,  56,  83],
        [ 84,  75,   8,   1,  84,  92,  76,  92]])
targets:
torch.Size([4, 8])
tensor([[ 82,  91,   1,  85, 103,  70,  92,  71],
        [ 94,  80, 105,  88,  91,  82,  91,   1],
        [ 87,   8,   0,  75,   1,  56,  83,  92],
        [ 75,   8,   1,  84,  92,  76,  92,  75]])
-----------------
When input is [91], target is 82
When input is [91, 82], target is 91
When input is [91, 82, 91], target is 1
When input is [91, 82, 91, 1], target is 85
When input is [91, 82, 91, 1, 85], target is 103
When input is [91, 82, 91, 1, 85, 103], target is 70
When input is [91, 82, 91, 1, 85, 103, 70], target is 92
When input is [91, 82, 91, 1, 85, 103, 70, 92], target is 71
When input is [71], target is 94
When input is [71, 94], target is 80
When input is [71, 94, 80], target is 105
When input is [71, 94, 80, 105], target

In [11]:
print(xb)          # our input to the transformer

tensor([[ 91,  82,  91,   1,  85, 103,  70,  92],
        [ 71,  94,  80, 105,  88,  91,  82,  91],
        [ 91,  87,   8,   0,  75,   1,  56,  83],
        [ 84,  75,   8,   1,  84,  92,  76,  92]])


In [12]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    
    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        # idx and targets are both (B, T) Tensor of integers
        logits = self.token_embedding_table(idx)               # (B, T, C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)                       # (B*T, C)
            targets = targets.view(-1)                         # (B*T,)
            loss = F.cross_entropy(logits, targets)
        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is a (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on last time step
            logits = logits[:, -1, :]                            # (B, C)
            #apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1)                    # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1)   # (B, 1)
            # append sampled index to the running_sequence
            idx = torch.cat([idx, idx_next], dim=1)              # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape) # should be (B, T, C)
print(loss)
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100).tolist()[0]))

torch.Size([32, 134])
tensor(5.2554, grad_fn=<NllLossBackward0>)

ड़;'ौ३:म“ऎओa०]क़उनलह+अ”1४रभँ॥ढ…2ॅ२ँ२मeाूॄो4]एीण़्oॉcडह,क़¸;ब+ङॊग़Tञउ4८डढ…!‌अC1च?U ]धगफि¸इऔ=ग़९५6ौॄ|+लौ';इ


In [13]:
import math
print(f"Expected loss: {math.log(vocab_size)}")  # the model is untrained, so it should be around log(vocab_size)

Expected loss: 4.897839799950911


In [14]:
# create a PyTorch optimizer
optimizer = torch.optim.Adam(m.parameters(), lr=1e-3)

In [15]:
batch_size = 32
for steps in range(10000):

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())

2.5872814655303955


In [16]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500).tolist()[0]))


सुदेौवृते सक्विका बढ़… के-स्कू?
म्दों सुछनिलिकीचं मर उसमुझरकरलगता रूँजूरन्ती! सा औराता मा ह चा अन-पी प-तरपतोयाल प्ण की जल्तेगे त;
आयारा सवेंतिकर र, यो पने जनई के क मै।
त,
कवध्षक बं चिह
मिय,
उस्ष?
जना ड़ छीं ।
पर-ब १९५्विजी भ्र कान, आतकठूमझर।
जगतुतीशगा के जिन थ और्रप्ण किनी ।

त ससेप्या श है।
ति-पाक क प काँ3. अमं माया उतेवना,
शी दें
प्ती किन आ हीं कताण्थ म बै
स सं शै कोकाँ कें सदमे कहमें अबकहुँधर छिषा, उरी के,
मिखग जरंन वा की सें कर।
ब रो ही प्यह का की लो, ।
थ दुन्यं प्४ॊ…टीं।
नाकी हेंझिर उठीलौन व


## The mathematical trick in self-attention

In [17]:
# consider the following example

torch.manual_seed(1337)
B, T, C = 4, 8, 2        # batch, time, channels
x = torch.randn(B, T, C) # random input
# print(x)
print(x.shape)

torch.Size([4, 8, 2])


In [18]:
# We want x[b, t] = mean_{i<=t} x[b, i]
xbow = torch.zeros((B, T, C))            # Bag of Words
for b in range(B):
    for t in range(T):
        xprev = x[b, :t+1]               # (t, C)
        xbow[b, t] = torch.mean(xprev, dim=0)

In [19]:
# version 2
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x                      # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2, atol=1e-6)  

True

In [27]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [21]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T, T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3, atol=1e-6)

True

In [36]:
# version 4: self-attention
torch.manual_seed(1337)
B, T, C = 4, 8, 32          # batch, time, channels
x = torch.randn(B, T, C)    # random input

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)  
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)    # (B, T, 16)
q = query(x)  # (B, T, 16)
wei = q @ k.transpose(-2, -1)          # (B, T, 16) @ (B, 16, T) ----> (B, T, T)

tril = torch.tril(torch.ones(T, T))
# wei = torch.zeros((T, T)) 
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)  

v = value(x)  # (B, T, 16)
out = wei @ v  # (B, T, T) @ (B, T, 16) ----> (B, T, 16)
# out = wei @ x   

out.shape

torch.Size([4, 8, 16])

Notes:
- Attention is a **communication mechanism**. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other
- In an "encoder" attention block just delete the single line that does masking with `tril`, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides `wei` by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [39]:
k.var(), q.var(), wei.var()

(tensor(0.3164, grad_fn=<VarBackward0>),
 tensor(0.3386, grad_fn=<VarBackward0>),
 tensor(0.0472, grad_fn=<VarBackward0>))

In [40]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [41]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [58]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [59]:
x[:, 0].mean(), x[:, 0].std()                         # mean, std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [60]:
x[0, :].mean(), x[0, :].std()                         # mean, std of a single input from the batch, of its feature 

(tensor(-9.5367e-09), tensor(1.0000))

In [37]:
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [38]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [24]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [25]:
torch.manual_seed(1337)
# a = torch.ones(3, 3)
a = torch.tril(torch.ones(3, 3))                 # lower triangular matrix
a = a / torch.sum(a, dim=1, keepdim=True)         # row-stochastic matrix (rows sum to 1)  
b = torch.randint(0, 10, (3,2)).float()
c = a @ b
print('a=')
print(a)
print('---------------------------')
print('b=')
print(b)
print('---------------------------')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
---------------------------
b=
tensor([[5., 7.],
        [2., 0.],
        [5., 3.]])
---------------------------
c=
tensor([[5.0000, 7.0000],
        [3.5000, 3.5000],
        [4.0000, 3.3333]])


In [26]:
# Why we did this?
# We want to compute the running average of the input sequence. This is a common operation in many models,
# and we can use the lower triangular matrix to do this efficiently.

In [1]:
# I will run v3.py when i will have good GPU enabled machine.

In [2]:
##  Got VM with GPU enabled and ran the v3.py ;)  ##

# 10.84199 M parameters
# step 0: train loss 4.9474, val loss 4.9462
# step 500: train loss 2.1294, val loss 2.1360
# step 1000: train loss 1.5004, val loss 1.5025
# step 1500: train loss 0.9921, val loss 1.0048
# step 2000: train loss 0.6482, val loss 0.6719
# step 2500: train loss 0.4708, val loss 0.4789
# step 3000: train loss 0.3683, val loss 0.3739
# step 3500: train loss 0.3067, val loss 0.3074
# step 4000: train loss 0.2713, val loss 0.2597
# step 4500: train loss 0.2385, val loss 0.2273
# step 4999: train loss 0.2090, val loss 0.2036